- speech/check_dataVals.m
Addition to check_dataVals to account for additional fields in the timeAdapt dataVals structure. (Following the single-change, single-pull request model, so other discussed changes will be separate)
> added fields to remove for timeAdapt dataVals structure

- plotting/plot_rawFmtTracks.m
Two changes in this one: 
1. variable groupId, which is groups(g), rather than relying on 1:length(groups) to provide the right index. groupId will be a number corresponding to a word/vowel lookup, depending on what groupings is. groupId is used to verify that a trial should be plotted in a subplot, and for the title. 
This should result in no or minimal changes for most studies. 
2. Aesthetic change: added statement to change number of columns based on how many groups there are. If there are fewer than 4 groups, nCols is set to the number of groups; else set at 4 (previous nCols). This decompresses the subplot displays for experiments with fewer groups, like timeAdapt (1 word), noisyfb (3 words) and should have no effect on anything else (like stroopVOT with 9 words). 
Have tested this …
> groupID add for timeAdapt

- speech/audapter_runFrames.m
- speech/audapter_runWav.m
Changes below to allow for a custom "p" parameter structure for running audapter on an existing signal. A use case I just had for this was needing to provide a different p.pertAmp to generate the noShift/shiftUp/shiftDown stimuli in the port speech perception experiment. I made the same change to check_audapterLPC as I did to audapter_runWav below, these were in a separate commit to current studies though. I'm realizing I messed up the order of operations a bit, as I should have done this first but you should be able to test these changes on check_audapterLPC and then we can do the move of experiment_helpers to free-speech.
> P argument in audapter_runFrames

- experiment_helpers/check_audio.m
Made a new, 6th input parameter for `check_audio.m` that accepts either 'signalIn' (default) or 'signalOut'. Pretty straightforward. I did some light testing and it worked.
I took the variable name 'buffertype' from `waverunner.m`, where that variable serves the same purpose as here.
> check_audio saves signalIn and signalOut info

- experiment_helpers/set_exptDefaults.m
- templates/modelExpt/run_modelExpt_audapter.m
- templates/modelExpt/run_modelExpt_expt.m
_This is a minor change, so I'll plan on merging EOD Friday unless something comes up._
Problem: New experiments, including vsaSentence and taimComp, have stimuli that are longer than one word and do not fit the same format (cf. timeAdapt, where the stimulus was longer than one word, but all followed the same format: "a capper," "a sapper," etc.). There are various functions that assume each cell array in expt.words is only one word long, meaning expt.words cannot contain the full text that the participant will be reading.
Solution: Add three new default fields to expt, namely `expt.stimulusText`, `expt.allStimulusText`, and `expt.listStimulusText`. expt.stimulusText will contain each of the full phrases participants will be shown, and it has a 1:1 mapping with expt.words. …
> new fields stimulusText in expt struct

- experiment_helpers/plot_duration_feedback.m
- experiment_helpers/set_exptDefaults.m
- speech/txt2ipa.m
This PR adds a few pieces of functionality:
* `plot_duration_feedback` has a switch to make it work better for sentence-length stimuli
* `plot_duration_feedback` can print out the vowel duration and return it as an output argument.
* Experiments not using the `expt.vowels` set of fields can set a new `expt.bIgnoreVowels` flag and don't have to worry about updating `txt2ipa`
* `set_exptDefaults` updated accordingly for the above
In `plot_duration_feedback`, `params.bFirst_offs_thresh` is a switch which controls how the utterance offset threshold is determined. It defaults to `1`, which was the previous behavior. When `1`, the offset is the **first** time the signal intensity reaches `params.offs_thresh`, after it has peaked. This works fine for single-syllable words. Multi-syllable words …
> new options for controlling plot_duration_feedback // add bIgnoreVowels

- experiment_helpers/check_rmsThresh.m
- speech/audioGUI.m
Carrie made some changes a while back to skip plotting the RMS threshold subplot for experiments on the iEEG cart PC (no second monitor). Handling this case instead of erroring seems like a reasonable thing to do in the context of any experiment.
> Do not attempt to plot into a sub plot axes object if it does not exist

- speech/audioGUI.m
Some simple code to inform someone who is tracking data that one of the trials they provided does not have data to display, and to skip to loading the next trial. This is useful in the context of experiments like mriSIS/iEEGSIS because there are "Listen" trials. We were previously just excluding them from data altogether, but this causes undesirable downstream effects in generating trial files with correct names (contents of the "trials" folder after tracking) and subsequently with the token field in dataVals.
> Conditional to skip a trial if it's signalIn is empty in data

- experiment_helpers/get_height.m
- templates/modelExpt/run_modelExpt_expt.m
Want to change the question the experimenter is asked while setting up expt from the biological sex of the participant to their height, as VTL strongly correlates with body height. 
Corresponding change to new run_EXPTNAME_expt scripts:
``if ~isfield(expt,'gender'), expt.gender = get_height; end``
> Wrapper function for get_gender, changes question to set expt.gender

- speech/audioGUI.m
- speech/waverunner.m
This update adds forced aligner user event functionality to waverunner, so that events are pulled in from existing TextGrids without needing to go through each trial in audioGUI.
I reorganized the way audioGUI pulls in the events to make it one contiguous code block, and copied it to waverunner (ideally we could make this into a function that both audioGUI and waverunner could call).
> Reorg forced aligner uev functionality and add to waverunner

- experiment_helpers/calc_vowelMeans.m
Just double-checking this fix -- currently this will break if you try to set ostInd as an argument (the variable ostInds only gets set if ostInd is empty).
> Fix typo re: ostInds

- experiment_helpers/calc_vowelMeans.m
Added a switch in `calc_vowelMeans` which will use data.ost_calc (i.e., user-specified OST values) if it's available. If that field doesn't exist or is empty for that trial, the function will use the old method of data.ost_stat (i.e., the original output OST values), which will always exist and be non-empty.
> add switch for ost_stat and ost_calc in calc_vowelMeans

- experiment_helpers/show_spectrogram.m
minor change in how spectrograms are displayed in the call to show_spectrogram. Now takes optional 'wide' or 'narrow' argument, defaulting to 'wide'.
> change to default to wideband spectrogram

- experiment_helpers/set_exptDefaults.m
I can't remember if this was talked about when we initially added date to the default expt file, but the situation with the trial number mismatch in the iEEG data collection have me thinking that it might be a good idea hold on to time of expt creation  alongside date. I realize that 'time' could be a confusing field name alongside 'timing', so we could just do something like setting date to `datetime('now')` instead. Also made a quick swap of get_gender to get_height as default behavior for asking for participant gender.
> Include current time (HH:MM:SS) as item stored in expt structure, get_gender->get_height

- experiment_helpers/randomize_stimuli.m
I was able to find that when setting up a randomly ordered vector of 0s and 1s, the script was using length(pertPair) instead of size(pertPair,2). This returns the length of pertPair (2 when a matrix, indicating 2 pairs. **Also** 2 when a vector containing just 1 pair, but the vector's length is 2) and causes an index out of bounds error. Size of the 2nd dimension should always return the correct number of pairs.
> Fix issue where number of perturbation trials is 1

- templates/modelExpt/run_modelExpt_expt.m
- utils/get_acoustLocalPath.m
- utils/get_acoustSavePath.m
- utils/get_exptLocalPath.m
- utils/get_exptSavePath.m
use savePath function in modelExpt instead of localPath so people know which one to use in future scripts built from the template. Also update helpdocs for localPath and savePath functions.
> Use savePath in modelExpt

- experiment_helpers/pause_trial.m
change to pause_trial to take in optional second argument, params, with assumed structure
params.pausetxt
params.conttxt
To be used for variables paustxt and conttxt, respectively. If empty or no second argument provided, defaults to original paustxt and conttxt. Change made to accommodate Mandarin-language pause and continue texts for simonToneLex. Runs properly with adaptRetest and simonToneLex.
> Mandarin pause

- experiment_helpers/set_exptDefaults.m
- utils/get_exptInds.m
Add functionality to set shiftNames, allShiftNames, and listShiftNames within `set_exptDefault`. With this change, we also don't have to specially set expt.inds.shiftNames in all the simon experiments anymore. See e.g. run_simonToneMatch_expt L387:
> expt.inds.shiftNames.noShift = find(strcmp(expt.listShiftNames, 'noShift'));
> expt.inds.shiftNames.shiftUp = find(strcmp(expt.listShiftNames, 'shiftUp'));
> expt.inds.shiftNames.shiftDown = find(strcmp(expt.listShiftNames, 'shiftDown'));
I've tested this on a mix of experiments using the shiftNames field and those not using it, and they all seem OK: vsaSentence, simonMultisyllable_v2, simonToneMatch, and coAdapt.
> add shiftNames to default expt.inds fields

- experiment_helpers/set_exptDefaults.m
- utils/get_exptInds.m
Fix issue from #34 where there's no input argument in `set_exptDefaults` to get passed to `get_exptInds`, the main workflow.
> Add input arg for expt.inds element names to set_exptDefaults

- experiment_helpers/randomize_stimuli.m
This adds to randomize_stimuli with the flag bAlternatePnp to do two different types of randomization. The default behavior is what the function originally did. The new behavior (which has to be explicitly flagged) does not require that any perturbed trial be flanked by an unperturbed trial, but only cares that no adjacent trials share word or condition. 
Also a couple of minor aesthetic changes (such as informing the participant that washout/baseline trials are not a good number). Includes documentation.
> New functionality for randomize_stimuli

- experiment_helpers/audapter_testcases.m
- experiment_helpers/check_segmentDuration.m
- experiment_helpers/check_segmentDuration_timeAdapt.m
- experiment_helpers/get_experiment_function.m
- experiment_helpers/get_gitPath.m
- experiment_helpers/get_ost.m
- experiment_helpers/get_pcf.m
- experiment_helpers/refreshWorkingCopy.m
- experiment_helpers/run_measureFormants_audapter.m
- experiment_helpers/run_measureFormants_audapterMEG.m
- experiment_helpers/set_ost.m
- experiment_helpers/set_pcf.m
- templates/modelExpt/run_modelExpt_audapter.m
1. Rework `get_gitPathm.` so it takes an input argument of the repository you want to return a path to. @carrien I just used exactly the code you sent me -- it worked and I didn't see any issues with it.
2. Fix calls to `get_gitPath` so they use the new format appropriately.
This PR should be merged at the same time as the [corresponding PR in the current-studies repo](https://github.com/blab-lab/current-studies/pull/30).
> call get_gitPath with new input arg structure

- experiment_helpers/adjustOsts.m
- experiment_helpers/plot_duration_feedback.m
Two changes to experiments that are broadly used in different experiments to have more functionality for taimComp specifically (but can be applicable to other experiments): 
1. adjustOsts: this is the function used to adjust OST settings in the middle of an experiment. Previously it would automatically take in the last 18 trials. This is fine when only a single word with a single OST file is being used. In taimComp, there are multiple words and multiple OST files. The addition allows you to specify that you want to work with some subset of files, using a "word" argument. This takes advantage of expt.inds.(words). 
trackingFileName is also optionally independently specified, for use in the case when, say, the words are "bus" and "best" but the OST is bVs 
2. plot_duration_feedback: this is …
> Additions to adjustOsts and plot_duration_feedback for taimComp

- utils/abbrev_dataPath.m
Quick fix to avoid errors when path string doesn't match the base path set in get_exptLoadPath.
> Bugfix for abbrev_dataPath

- speech/audioGUI.m
- utils/savecheck.m
This PR is associated with [another one](https://github.com/blab-lab/wave_viewer/pull/4) in blab-lab/wave_viewer.
1. Changes were necessary in `audioGUI.m` to accommodate the jump-to trial functionality in wave_viewer. Namely, the `for` loop on L63 is now a `while` loop, so that the trial number can dynamically change between iterations of the loop.
2. `savecheck` is what displays the "are you sure you want to overwrite that file?" popup used in many lab functions. `savecheck` was heavily revised. It now displays a different message which splits out the filepath from filename. It also uses TeX formatting now, which allows for coloring in the file name for emphasis, and increasing the font size. Using TeX required some additional code to accommodate special characters not being interpreted …
> Go to previous trial for audioGUI. Clearer 'are you sure?' overwrite message

- stimulus_generation/continuum_durTier.Praat
edit to a Praat script that is used to create duration continua to allow for non-integer millisecond steps (e.g. 0.5 ms) and non-integer start/finish step values
> allows for noninteger steps

- experiment_helpers/run_passageReading.m
A couple functions have the same code currently, which displays a few screens and then starts Audapter for the participant to read the "rainbow" passage. This function houses that code and will eventually replace the code that lives individually in those functions. This function also makes the language a little more general (doesn't reference "now starting adaptation section 2").
Functions that will eventually be affected: run_adaptRetest_expt, restart_adaptRetest_expt, and run_cerebAAF_expt. Once this is in free-speech, I'll update those other functions to reference this instead of having the code just within those functions.
> new function for rainbow passage reading

- experiment_helpers/pause_trial.m
Previously the "we will now continue" text would overlay the "paused" text and not be able to be read properly. This has been fixed by using the standard functions we use for drawing and deleting text now: `draw_exptText` and `delete_exptTest`.
Tested with:
* simonSyllableTransfer
* iEEGcomp
* coAdapt
* cerebAAF
> draw/delete text properly with draw_exptText and delete_exptText

- speech/audioGUI.m
Add new functionality to allow user to **toggle formants off from the start** when launching audioGUI.
This was previously requested by Robin for one of her studies (where they weren't helpful during segmentation and obscured the view of the spectrogram). I also want to use this for segmentation practice I'm setting up for new students, for similar reasons.
This change should be merged at the same time as another change to wave_viewer: https://github.com/blab-lab/wave_viewer/pull/5
> input arg that feeds into plot_params.show_formants

- experiment_helpers/setup_exptFigs.m
Previously, `setup_exptFigs` was only designed to work with the primary monitor in the left position, and the participant's monitor in the right position. The Matlab figure with the participant's instructions was hard-coded to display to the right of the main display.
Now, we check if the second display is to the right or left of the main monitor, and display the figure on the correct screen.
I tested this with both orientations in an experiment which uses the default experiment figure setup.
This does not affect experiments where we assume there is only one screen, like the iEEG setup. Those experiments use a different function to create experiment figures.
> Set participant screen based on window orientation

- experiment_helpers/run_passageReading.m
When entering/leaving the passage-reading section of adaptRetest where the participant gets live monitoring feedback, now the experimenter has to press Enter (via `input` command) instead of any key working to enter/leave. Some eager participants were messing this up.
> Require Enter keypress to move on

- audapter_viewer/audapter_viewer.m
Adds support for INTENSITY_AND_RATIO_BELOW_THRESH heuristic in audapter_viewer
This should be merged, now that [the new mex file (version b2.3) has been merged](https://github.com/blab-lab/audapter_mex/pull/8) and will be used on lab computers.
> Work with new heuristic

- speech/gen_dataVals_from_wave_viewer.m
Sort user events first-to-last in `trialparams.event_params` within a trial, if they are not indexed in linear order. This prevents problems when generating a multisegment dataVals file, like in vsaSentence.
> Update gen_dataVals to sort user events

- experiment_helpers/check_rmsThresh.m
- experiment_helpers/run_checkLPC.m
- experiment_helpers/run_measureFormants_audapter.m
This is a replacement to #69 , which I kind of messed up by rebasing and not merging with master for 6 months.
@carrien , the new things are:
- Line 20 to initialize the empty struct properly
- lines 36-45 for the expt.amplcalc default params, now that #92 is merged
- lines 51-56 for correctly setting these fields
- Updated `run_measureFormants_audapter` to use the new expt.amplcalc fields
Original description:
> 
> This function can be called in contexts where the experiment-programmer wants to collect information about a participant's LPC order or default vowel space area in a pretest phase. Previously, this was achieved by similar or identical lines of code being used in many run_..._expt functions.
> 
> This function adds a few features rarely implemented in other experiments:
> * …
> Create function run_checkLPC

- audapter_viewer/audapter_viewer.m
- audapter_viewer/gen_ostUserEvents_timeAdapt.m
There was a bug in audapter_viewer when using recalculate all only, where the new OST parameters were not saved in the data structure. So if you went to a different trial, the old OST params would be there instead.
> bugfix for recalc all

- experiment_helpers/check_audio.m
- speech/waverunner.m
**Issue**: if you have run MFA on a dataset, when you run waverunner, it adds those events to trialparams.event_params. That in itself is fine, but it doesn't add anything else to event_params.  
The main problem is that, specifically, it does not add the field is_good_trial. If you try to run check_audio on the data again, it will error out on a trial.mat file that was only created during waverunner because check_audio runs this check:  
`if ~isfield(trialparams,'event_params') || trialparams.event_params.is_good_trial`
In the trials with MFA info but nothing else, event_params is a field, but is_good_trial does not exist.  
**Both solutions have been implemented**: 
1. In waverunner, when it adds the event information from MFA, also check for if is_good_trial exists. If it doesn't, …
> fix for using check_audio after MFA in waverunner

- experiment_helpers/pause_trial.m
- experiment_helpers/set_exptDefaults.m
Change the text that shows up on screen when the participant pause so that it DOESN'T say how to unpause. The experimenter will either unpause or tell them when to do that.
This also adds a `pauseParams` field to `expt` via `set_exptDefaults`. The name of the field and sub-fields are aligned with previous experiments, notably simonToneLex, which changed `pause_trial` to add a params input argument.
> Change pause text

- experiment_helpers/check_rmsThresh.m
- experiment_helpers/run_checkLPC.m
- experiment_helpers/run_measureFormants_audapter.m
- experiment_helpers/set_exptDefaults.m
Condense 2nd and 4th input params.
Get rid of the 'mean' method of calculating RMS value. Make a new method called 'peak_window'.
**This branch should not be merged immediately**. It should be timed with a change to current-studies which changes how input parameters are used for a small number of functions.
> `check_rmsThresh` use 2nd param; use peak

- speech/gen_dataVals_from_wave_viewer.m
Addresses issue #106 
The function now generates a new variable `dataVals_params` which gets saved in the file `dataVals.mat` alongside the variable `dataVals`. Tested in simonSingleWord (bMultisegment = 1) and noGoAdapt (bMultisegment = 0).
> add logging to gen_dataVals_from_wave_viewer

- audapter_viewer/get_ostEventNamesNumbers.m
This is required for simonPhrase to call audapter_viewer properly. I created #114 to address the fact that `get_ostEventNamesNumbers` should probably work out-of-the-box for simon experiments, but in fact requires updates to not error out.
> Update to add OST event names for simonPhrase

- experiment_helpers/calc_pertField.m
- experiment_helpers/plot_perturbations.m
These functions are used in experiments where VSA figures are plotted, then the user is asked to confirm that the figure looks correct. Previously, sometimes the figure would **not** actually appear, but the code would continue to the section where it prompts the user to confirm that the figure looks good. This is apparently [a known issue](https://www.mathworks.com/matlabcentral/answers/95752-why-does-pause-0-fail-to-update-the-figure-in-matlab-7-0-1-r14sp1) related to how Matlab uses the "event queue".
This PR fixes the issue by adding the call `drawnow` at the end of functions which plot a thing and are frequently called in the middle of another function.
> Add `drawnow` to plotting functions

- experiment_helpers/check_audapterLPC.m
Adds 2 features to the check_audapterLPC gui:
1. New "Reference point" selectable list which can switch between "mean" (default) and "median"
2. New "Play" button which plays audio for the selected trial
Other code changes:
3. Added a second input parameter "params" which controls (1.) mean vs median reference point at startup, and (2.) how the selected trials are picked at startup. For "mean" reference point, it's the trial furthest from the mean. For "median" reference point, it's the trial closest to the median.
4. Shifted several of the GUI buttons on the right panel to make room for "reference point" section
5. Previously, selecting a new trial (ie, clicking on a dot) would set the formants to "visible" and vowel bounds to "visible", even if the user had previously toggled them off. …
> check_audapterLPC median point & play audio button

- experiment_helpers/run_mfa.m
The 'dictionary' and 'language' arguments in the MFA v3 system command were backwards. I realized this while testing a custom dictionary for vsaPD.
The system commands is correct in the part of this function which deals with MFA v1, so there's no need to edit that part of the code.
> Fix MFA v3 system command input argument order

- speech/check_dataVals.m
Previously, if a trial has all NaNs as the formant values, check_dataVals would error. This situation could occur if there was a single user event after all tracked formants, like in the picture below. (Rare, but it happened once.)
Now, that trial appears in the NaNFTrials category. It isn't plotted (there's nothing to plot), but the NaNFTrials button appears red, and the alert message will display "1 trial(s) selected."  I updated the check_dataVals KB page to explain this situation, since it's unusual to have an error trial that isn't plotted.
I also updated the alert message from "# trials selected" to "[#] trial(s) selected."
> check_dataVals handle all NaNs trial

- utils/savecheck.m
We use TeX formatting when displaying the "are you sure you want to overwrite this file?" popup generated by `savecheck.m`. The question dialogue box `questdlg` is hardcoded to split up long strings, eg filepaths, into 75-character chunks which are then put into a cell array of character vectors. This chunking is done by `textwrap`. This chunking doesn't take into consideration TeX escape characters. So when the escape character is at the end of one char vector and the character that's supposed to be escaped is at the beginning of the next char vector, Java throws lots of errors and the text is not parsed properly.
Normally this problem presents itself when there is a filepath with an underscore, and the underscore just so happens to be the 75th (or 150th, etc) character in the file path. …
> add newlines in paths to fix TeX parsing

- experiment_helpers/calc_pertField.m
There are two fields called 'pertF1' and 'pertF2' set in the Audapter parameters struct in MATLAB. Note that the "F" is capital in the field names. We have several functions which set Audapter parameter fields pertf1 and pertf2 (lowercase f). Some experiments thus have the expected Audapter field pertF1 with its default value, while pertf1 has the "real" values. This is confusing for anyone who isn't aware of the difference.
This pull request unifies all functions I could find to use the correct field names: pertF1 and pertF2.
Separate from fixing the code, I already fixed the actual expt.mat files. These settings are stored in expt.audapterParams. I tried to identify all experiments that had set expt.audapterParams.pertf1 or pertf2 (lowercase). I then set expt.audapterParams.pertF1 and …
> capitalize pertF1 and pertF2 field names

- audapter_viewer/get_ostEventNamesNumbers.m
Fix to #114
In other words, previously, if you tried to run audapter_viewer on a dataset with a "space"-based shift where `get_ostEventNamesNumbers.m` didn't specify the shift names, get_ostEventNamesNumbers would error out because there was no "trigger" event name. (The trigger event is the primary OST event; typically when the perturbation turns on.)
Now, as a default/backup setting, get_ostEventNamesNumbers defaults to name the "trigger" event "ost2," and label the trigger event at OST==2.
> set backup trigger event name if none specified

- experiment_helpers/setup_exptFigs.m
All changes to `setup_exptFigs`
You can view MATLAB's screen information with `get(0, 'monitorPositions'). It tells you how many monitors MATLAB thinks you have, and what indexed ordered MATLAB puts them in. The order is often but not always from leftmost to rightmost. You do not have control over what indexed number MATLAB assigns to a monitor. The "MATLAB" indices of monitors does not always match up with the indices of monitors in Windows display settings. What this means is that, when you start MATLAB, you don't know for sure which physical monitor is considered by MATLAB to be "monitor 1". 
There are three options:
1. Assume that MATLAB isn't going to randomly change or flip flop how it determines which monitor is which, and assume that the "main display" in Windows display settings …
> Change to logic for picking which monitor an experiment-running figure displays on
