plotting/plot_centering.m
plotting/plot_centering_legacy.m
plotting/plot_init2mid.m
plotting/plot_init2mid_multi.m

Plot centering is now a wrapper for plot_init2mid and plot_init2mid multi. Can now pass in a custom plotting parameters structure (p), supply specific conds2plot and the corresponding formant data is passed into the internal functions. Figure handles for each plot generated are returned. 
I had saved a draft version of plot_init2mid.m to free speech so that's why it's saying there are modifications rather than it just being a new file. 
Renamed the old version of the script to plot_centering_legacy.m in case someone needs it.

Plot centering update

---

speech/audapter_runFrames.m

Part of project that adds a "change OSTs" button in check_audapterLPC that would go to audapter_viewer.

calcOST field is retained after running audapter offline

---

experiment_helpers/check_audapterLPC.m

Allows for calling check_audapterLPC mid-experiment, when length of data.mat doesn't match expt.ntrials. (Also changes loop variable to "v" for vowels so that "i" consistently means trials in this file.)

Allow for checking LPC with partial data

---

experiment_helpers/askNChoiceQuestion.m
speech/txt2arpabet.m

txt2arpabet was a stray change as well. Fixed merge conflict to revert to main branch.

Poorly named branch, just nChoiceQuestion minor change

---

experiment_helpers/randomize_stimuli.m

As title says. Includes safety release for while statement as well. Tested for 1000 iterations and did not break.

fixed a bug with adjacency conditions across block boundaries

---

stimulus_generation/bpm2isi.m
stimulus_generation/continuum_durTier.Praat
stimulus_generation/gen_gammaMetronome.m
stimulus_generation/gen_sinetoneAnisos.m
stimulus_generation/gen_sinetoneDurs.m
stimulus_generation/gen_sinetoneTempos.m
stimulus_generation/isi2bpm.m
stimulus_generation/lengthenTransition.Praat

Following guidance to put more general files into free-speech and also to have more informative folders. This is I guess what I would consider "experiment_helpers" esque but specifically there are multiple files for helping generate different kinds of stimuli. So far they've mostly been used in timitate but at least two of them are general to our paced cerebellar experiments, and the Praat scripts will likely apply to future studies.

moving some more general functions to free-speech

---

speech/gen_dataVals_from_wave_viewer.m

The github diffing is super confused. The only new things are adding the `try` in L100 and the `catch` clause in L163, and everything in-between got indented.

print trial number to screen if errors during execution

---

experiment_helpers/randomize_wordOrder.m

takes randomize_wordOrder out of current-studies and into free-speech

Rand word order

---

speech/check_dataVals.m

Worked with light testing.
In addition to main functionality, also removed one redundant IF statement on old line 169. (Maybe there used to be just one `jumpTrials` category?)

add input arg for error-checking parameters

---

experiment_helpers/get_gitPath.m

uses run_cerebTimeAdapt_expt.m as the representative function to find the cerebellar-battery study. Tested refreshWorkingCopy using this and it worked

added cerebellar-battery as a possible repo

---

experiment_helpers/randomize_stimuli.m
experiment_helpers/refreshWorkingCopy.m

Rwc filepath

---

audapter_viewer/audapter_viewer.m

for some reason I just never form the variable oldThresh. Fixed it here.

bugfix for single trial restore

---

speech/check_dataVals.m

With my recent change to `check_dataVals`, you can now populate the errorParams input argument to specify how the function should decide if a trial is an "error trial" or not. This PR updates the "late trial" error. The "late trial" error previously worked in one of two ways:
1. If it had info in expt about the trial length, it would check to see if the vowel ended in the first 96% of the trial. If it ended it the last 4%, error.
2. If it DID NOT have info about trial length, it would check that the vowel ended after the first 1.5 seconds of the trial. If it ended more than 1.5 seconds since trial start, error.
That same functionality exists, but now the 4% part and the 1.5 seconds part are parameterized as `errorParams.lateThresh_ratio` and `errorParams.lateThresh_absolute`.
I also …

parameterize definition of late trials in check_dataVals

---

audapter_viewer/audapter_viewer.m

fix filepaths for non-default SMNG save locations

---

audapter_viewer/timeAdapt_pcfAnalysis.m

function needed for various time adaptation experiments including in cerebellar battery

putting pcf analysis into FS

---

audapter_viewer/calcPertValue.m
experiment_helpers/check_segmentDuration.m
experiment_helpers/get_segmentDuration.m

another function for cerebellar battery

Moving from CS

---

plotting/plot_sigprocParams_byCond.m

This didn't work before, because `plot` doesn't want the output of `histogram`. Now it works and plots the histogram.
Also added some carriage returns for clarity.

fix call to histogram

---

templates/modelExpt/plot_modelExptPaperFigs.m

Carrie, feel free to add or remove "template" stuff that you'd like to see based on typical use cases. Or send me notes and I'll try to iterate.

Model paper figs

---

stats/add2anovars.m

Quick fix to the help comments.

Change help message to match correct argument order

---

speech/gen_dataVals_from_wave_viewer.m

Found a bug in gen_dataVals_from_waveviewer where cond field wasn't being created in dataVals and condition was being put in color field

fix bug where cond wasn't assigned to dataVals

---

templates/modelExpt/gen_fmtMatrix_modelComp.m
templates/modelExpt/run_modelComp_audapter.m
templates/modelExpt/run_modelComp_expt.m

Created some compensation functions that can be used as example functions. I tested the workflow of `run_modelComp_expt` and `run_modelComp_audapter`, then `gen_dataVals_from_audapter`, then another new function `gen_fmtMatrix_modelComp`, then `plot_fmtMatrix` with basic inputs. This did produce results successfully, so I think the code is in a decent enough state to share with UC Irvine, at least.

Model compensation function

---

.gitignore
audapter_viewer/gen_ostUserEvents_timeAdapt.m
experiment_helpers/run_measureFormants_audapter.m
experiment_helpers/run_measureFormants_audapterMEG.m

These are the changes that are necessary in free-speech for SMNG. I will have my own set of changes (have to add study-code as a possibility in get_gitPath). I'm pretty sure this is the way to merge the SMNG-general changes only...

changes for gitpath instead of exptrunpath

---

templates/modelExpt/run_modelComp_audapter.m
templates/modelExpt/run_modelComp_expt.m
templates/modelExpt/run_modelExpt_audapter.m
templates/modelExpt/run_modelExpt_expt.m

Minor changes to model experiment code based on conversation with Carrie on Wed. July 2:
1. Added a comment explaining what the `add_adjustOstButton` function is and when it should be un-commented out.
2. Stopped using the 'session' field for the expt struct when making a subfolder 'dur' for duration training.

Model expt comment and field name

---

jnd/get_nextStepSize.m
jnd/get_stimuliBasedOnStep.m
jnd/get_stimulusSequence.m
jnd/run_staircase_ptb.m

@carrien This PR is doing the thing we talked about mid-July: adding several JND-related functions from the cerebellar-battery repo to free-speech and putting them in a new 'jnd' folder. This free-speech PR will be merged simultaneously [with this one](https://github.com/blab-lab/cerebellar-battery/pull/24) in the cerebellar-battery repo which removes the functions.
Since it's a new folder, people will need to add the new free-speech folder to their MATLAB path. After that, functionality is identical. I will notify people to update the MATLAB path on their own computers, and I'll do it on shared lab computers.

Just Noticeable Difference functions from cerebellar-battery

---

speech/audioGUI.m

Fixes https://github.com/carrien/free-speech/issues/139

Display trial number when ending out of audioGUI
